name: "GitOps Deployment"
on:
  push:
    branches: [server]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Remove Existing Compose File
        run: |
            cd /opt/dinandos-homelab
            sudo rm compose.yml

      - name: Build Compose File
        run: |
            cd /opt/dinandos-homelab
            echo "name: homelab-stack" > compose.yml
            echo "include:" >> compose.yml

            find . -mindepth 2 \( -name "compose.yaml" -o -name "docker-compose.yml" \) | sed 's|^\./||' | while read -r path; do
              echo "  - $path" >> compose.yml
            done

      - name: Deploy Compose Stack
        run: |
            cd /opt/dinandos-homelab
            sudo docker compose -f compose.yml up -d --remove-orphans

      - name: Success Notification
        if: success()
        run: echo "Deployment succesvol voltooid."

      - name: Failure Notification
        if: failure()
        run: echo "Deployment gefaald. Controleer de runner logs."