name: "File Configuration Check"
on: [push]
jobs:
  validate:
    runs-on: self-hosted
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          path: /tmp/dinandos-homelab
          clean: false
      
      - name: Verifing Configuration Files
        run: |
            cd /tmp/dinandos-homelab/scripts
            sudo chmod +x ./verify-configs.sh

            cd ..
            ./verify-configs.sh

      - name: Cleanup Cloned Repository
        run: sudo rm -rf /tmp/dinandos-homelab