name: "Caddy Validation"
on: [push]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Caddyfile
        run: |
          docker run --rm \
            -v $(pwd)/caddy-full:/etc/caddy \
            caddy:latest caddy validate --adapter caddyfile --config /etc/caddy/Caddyfile