name: "Nightly Backup"
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: self-hosted
    steps:
      - name: Create Backup Directory
        run: sudo mkdir -p /backups

      - name: Run Backup Script
        run: |
          # Variabelen instellen
          SOURCE_DIR="/opt"
          BACKUP_DIR="/backups"
          TIMESTAMP=$(date +%Y-%m-%d_%H-%M)
          FILENAME="homelab_backup_$TIMESTAMP.tar.gz"

          echo "Start backup van $SOURCE_DIR..."

          sudo tar -czf $BACKUP_DIR/$FILENAME $SOURCE_DIR

          echo "Backup opgeslagen als: $BACKUP_DIR/$FILENAME"

      - name: Cleanup Old Backups
        run: |
          echo "Oude backups opruimen..."
          sudo find /backups -name "homelab_backup_*.tar.gz" -mtime +14 -delete
          echo "Opruimen voltooid."